name: Python Workflow with Semver

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      run: python example.py

    - name: Install semver-tool
      run: |
        curl -sSL https://github.com/fsaintjacques/semver-tool/archive/3.0.0.tar.gz | tar xvz
        mv semver-tool-3.0.0/semver /usr/local/bin/
        chmod +x /usr/local/bin/semver

    - name: Get version from semver-tool
      id: semver
      run: echo "::set-output name=version::$(semver -c echo ${{ github.ref }} | cut -c 11-)"

    - name: Display Semver version
      run: echo "Semver version is ${{ steps.semver.outputs.version }}"
