name: Bump Version Workflow

on:
  push:
    branches:
      - main

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install semver-tool
      run: |
        curl -sSL https://github.com/fsaintjacques/semver-tool/archive/3.0.0.tar.gz | tar xvz
        mv semver-tool-3.0.0/src/semver /usr/local/bin/
        chmod +x /usr/local/bin/semver

    - name: Bump version with semver
      id: semver
      run: |
        # Bump the version in your version file or other relevant files
        new_version=$(semver bump patch $(semver -c echo ${{ github.ref }} | cut -c 11-))
        echo "New version is $new_version"

        # Commit the changes
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git add path/to/version/file  # Adjust the path as needed
        git commit -m "Bump version to $new_version"

        # Push the changes back to the repository
        git push origin main

    - name: Display New Version
      run: echo "New version is ${{ steps.semver.outputs.version }}"
