name: Bump Version Workflow

on:
  push:
    branches:
      - main

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get latest tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - name: Install semver-tool
        run: |
          curl -sSL https://github.com/fsaintjacques/semver-tool/archive/3.0.0.tar.gz | tar xvz
          mv semver-tool-3.0.0/src/semver /usr/local/bin/
          chmod +x /usr/local/bin/semver

      - name: Bump version with semver
        id: bump-semver
        run: |
          # Bump the version in your version file or other relevant files
          new_version=$(/usr/local/bin/semver bump patch ${{ steps.get-latest-tag.outputs.tag }})
          echo "New version is $new_version"
          echo "::set-output name=semver_tag::${new_version}"

      - name: Created tag
        run: echo "tag ${{ steps.bump-semver.outputs.semver_tag }}"

      - name: Push new tag
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
        run: git push origin ${{ steps.bump-semver.outputs.semver_tag }}-dev

      - name: Display New Version
        run: echo "New version is ${{ steps.bump-semver.outputs.semver_tag }}-dev"
